_.delete  # unused method (src/schemashift/registry.py:31)
_.delete  # unused method (src/schemashift/registry.py:54)
_.delete  # unused method (src/schemashift/registry.py:92)
_.load_schema  # unused method (src/schemashift/registry.py:99)
_.required_columns  # unused method (src/schemashift/target_schema.py:62)
_.validate_eager  # unused method (src/schemashift/target_schema.py:107)
